config/routes.rb
AmitTestBlog::Application.routes.draw do

  devise_for :admins

  devise_for :users

  root to: "posts#index"

  resources :posts do
    resources :comments, only: [:new, :show, :create]
  end

  namespace :admin do
    resources :posts
    resources :comments
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id

  belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  
  attr_accessible :body, :subtitle, :title, :user_id, :photo, :photo_cache

  belongs_to :user
  belongs_to :admin

  has_many :comments

  validates :body, presence: true

  validates :subtitle, presence: true

  validates :title, presence: true

  # validate :user_or_admin_exists

  # private

  # def user_or_admin_exists
  #   if !(user_id.blank? ^ admin_id.blank?)
  #     errors.add_to_base("Need either a user or admin ID")
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @posts = Post.all

    respond_to do |format|
      format.html
    end
  end

  def create
    @post = current_admin.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_path, notice: 'Good job creating your post. You must be some sort of genius.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def new
    @post = current_admin.posts.new(params[:id])
    
    respond_to do |format|
      format.html
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to admin_posts_path, notice: 'Your post was successfully updated. Admins rule.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html {redirect_to admin_posts_path}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Hello comment was posted dude"}
      else
        format.html { render action: "new"}
      end
    end
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all

    respond_to do |format|
      format.html
    end
  end

  def create
    @post = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Good job creating your post. You must be some sort of genius.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def new
    @post = current_user.posts.new
    
    respond_to do |format|
      format.html
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end

  def update
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Your post was successfully updated. Dummy.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html {redirect_to posts_url}
    end
  end
end

app/controllers/posts_controller_amit.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all

		respond_to do |format|
			format.html
		end
	end

	def show
		@post = Post.find(params[:id])

		respond_to do |format|
			format.html
		end
	end

	def new
		@post = Post.new

		respond_to do |format|
			format.html
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(params[:post])

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
			else
				format.html { render action: "new" }
			end
		end
	end

	def update
		@post = Post.find(params[:id])

		respond_to do |format|
			if @post.update_attributes(params[:post])
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
			else
				format.html { render action: "edit" }
			end
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		respond_to do |format|
			format.html { redirect_to posts_url }
		end
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/newadmin.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if admin_signed_in? %>
  <%= link_to "Sign Out", destroy_admin_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_admin_session_path %>
<% end %>

app/views/admin/posts/_editnav.html.erb
<%= link_to 'Edit this Post', edit_admin_post_path(post) %>

<%= link_to 'Delete this Post', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/admin/posts/_form.html.erb
	<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li><%= message %>
		<% end %>
	</ul>

	<%= form.label :title, "What's your title?" %><br>
	<%= form.text_field :title, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :subtitle, "What's your subtitle?" %><br>
	<%= form.text_field :subtitle, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :body, "What's your content?" %><br>
	<%= form.text_area :body, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :photo %><br>
	<%= form.file_field :photo %>
	<%= form.hidden_field :photo_cache %>
	<br>
	<br>
	<%= form.submit %>

app/views/admin/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/admin/posts/edit.html.erb
<h1>Edit this fucking post</h1>

<%= form_for [:admin, @post] do |form| %>
	<%= render form %>
<% end %>

<%= link_to 'Show', admin_post_url %>
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>These are all the posts ever made</h1>
<% if admin_signed_in? %>
  <p>Signed in as... <%= current_admin.email %></p>
<% else %>
  <p>This blog is way more fun if you're signed in. But you're not.<p>
<% end %>

<% @posts.each do |post| %>
  <h1><%= post.title %></h1>
  <p><%= image_tag post.photo.url if post.photo? %></p>
  <h2><%= post.subtitle %></h2>
  <p>Author: <%= post.user.email %></p>
  <p><%= post.body %></p>
  <p><%= link_to 'Permalink', admin_post_url(post) %></p>
  
  <%= render partial:"editnav", locals: { post: post } %>
  
  <hr>

<% end %>

<p><%= link_to 'Write a Post', new_admin_post_path if admin_signed_in? %></p>

app/views/admin/posts/new.html.erb
<h1>Create a new post, genius. Or name all the members of the Wu-Tang Clan. Whatevs. Do something.</h1>

<%= form_for [:admin, @post] do |form| %>
	<%= render form %>
<% end %>

app/views/admin/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= image_tag @post.photo.url if @post.photo? %></p>
<h2><%= @post.subtitle %></h2>
<p><%= @post.body %></p>
<p><%= @post.user.email %></p>



<hr>
<% if admin_signed_in? %>
  <%= render partial:"editnav", locals: { post: @post } %>
<% end %>

<br>
<br>
<hr>
<%= link_to "Leave a comment", new_post_comment_path(@post) %>

<% @post.comments.each do |comment| %>
  <hr>

  <p><%= comment.content %></p>
  <%= link_to "Show comment", post_comment_path(@post, comment.id) %>
<% end %>

<br>
<br>
<hr>

<%= link_to 'All Posts - Admin Section', admin_posts_path %>

app/views/admin/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/comments/_form.html.erb
<%= form.label :content, "Blather on, friend. We will listen to you:" %>

<br>

<%= form.text_area :content %>

<br>

<%= form.submit %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h2>Leave a comment on <%= @post.title %></h2>

<%= form_for [@post, @comment] do |form| %>
  <%= render form %>
<% end %>

app/views/comments/show.html.erb
<h3><%= @comment.content %></h3>

<%= link_to 'Back to Posts', @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AmitTestBlog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">AmitTestBlog</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_editnav.html.erb
<%= link_to 'Edit this Post', edit_post_path(post) %>

<%= link_to 'Delete this Post', post, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>

	<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li><%= message %>
		<% end %>
	</ul>

	<%= form.label :title, "What's your title?" %><br>
	<%= form.text_field :title, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :subtitle, "What's your subtitle?" %><br>
	<%= form.text_field :subtitle, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :body, "What's your content?" %><br>
	<%= form.text_area :body, placeholder:"Why do you deserve to be listened to?" %>
	<br>
	<br>
	<%= form.label :photo %><br>
	<%= form.file_field :photo %>
	<%= form.hidden_field :photo_cache %>
	<br>
	<br>
	<%= form.submit %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit this fucking post</h1>

<%= form_for @post do |form| %>
	<%= render form %>
<% end %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>These are all the posts ever made</h1>
<% if user_signed_in? %>
  <p>Signed in as... <%= current_user.email %></p>
<% else %>
  <p>This blog is way more fun if you're signed in. But you're not.<p>
<% end %>

<% @posts.each do |post| %>
  <h1><%= post.title %></h1>
  <p><%= image_tag post.photo.url if post.photo? %></p>
  <h2><%= post.subtitle %></h2>
  <p>Author: <%= post.user.email %></p>
  <p><%= post.body %></p>
  <p><%= link_to 'Permalink', post %></p>
  
  <% if user_signed_in? %>
    <% if post.user.email == current_user.email %>
      <%= render partial:"editnav", locals: { post: post } %>
    <% end %>
  <% end %>
  
  <hr>

<% end %>

<p><%= link_to 'Write a Post', new_post_path if user_signed_in? %></p>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= image_tag @post.photo.url if @post.photo? %></p>
<h2><%= @post.subtitle %></h2>
<p><%= @post.body %></p>
<p><%= @post.user_id %></p>



<hr>
<% if user_signed_in? %>
<% if @post.user.email == current_user.email %>
  <%= render partial:"editnav", locals: { post: @post } %>
<% end %>
<% end %>

<br>
<br>
<hr>
<%= link_to "Leave a comment", new_post_comment_path(@post) %>

<% @post.comments.each do |comment| %>
  <hr>

  <p><%= comment.content %></p>
  <%= link_to "Show comment", post_comment_path(@post, comment.id) %>
<% end %>

<br>
<br>
<hr>

<%= link_to 'All Posts', posts_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>